### ISSUE TITLE
How to start new JSweet project 

### ISSUE THREAD

**Issue by travelbasys** [cincheo/jsweet-eclipse-plugin#18]
Hello...
How do I start a new JSweet project in Eclipse from the ground up using the plugin?
There is no New.../Project.../New JSweet Project.

Should I start with a new Maven Project and then "promote" it to a JSweet one?
If yes, how?

Thanks.

**Comment by renaudpawlak** [comment]
Hey. A JSweet project is just a regular Java project (typically, you can make it a Maven project). 

So (assuming that a JSweet Eclipse plugin is installed), create a Maven project. Then, right-click on the project: ``Configure > Enable JSweet builder...``

And eventually, use the ``Properties > JSweet`` menu on the project to configure how JSweet generates code.

**Comment by travelbasys** [comment]
Thanks.
I just discovered
http://www.jsweet.org/eclipse-plugin/

A link in README.md might be a good idea or updating README, too.
Thanks, all the same.
