### ISSUE TITLE
System.out.print compiled wrong

### ISSUE THREAD

**Issue by travelbasys** [cincheo/jsweet-eclipse-plugin#20]
Hello.
I am using the _jsweet-quickstart_ project downloaded from GitHub.

I wrote another simple class:

```
package quickstart;

public class SimpleTest {

	public static void main(String[] args) {
		StringBuilder sb = new StringBuilder();
		sb.append("Test");

		System.out.print(sb.toString());
	}

}

```

After compiling I got the following _SimpleTest.js_:
```
/* Generated from Java with JSweet 2.0.0-rc1 - http://www.jsweet.org */
var quickstart;
(function (quickstart) {
    var SimpleTest = (function () {
        function SimpleTest() {
        }
        SimpleTest.main = function (args) {
            var sb = { str: "", toString: function () { return this.str; } };
            /* append */ (function (sb) { return sb.str = sb.str.concat("Test"); })(sb);
            java.lang.System.out.print(/* toString */ sb.str);
        };
        return SimpleTest;
    }());
    quickstart.SimpleTest = SimpleTest;
    SimpleTest["__class"] = "quickstart.SimpleTest";
})(quickstart || (quickstart = {}));
quickstart.SimpleTest.main(null);
```

I was quite impressed, how cleverly the _StringBuilder.append_ method is emulated.
But: _System.out.print_ is just converted to _java.lang.System.out.print_.
My Browser (Chrome) then complains in the developer console:

> Uncaught ReferenceError: java is not defined
>     at Function.SimpleTest.main (SimpleTest.js:10)
>     at SimpleTest.js:17

Thanks for advice.

**Comment by travelbasys** [comment]
Oops...
Forgot to mention: I am using Eclipse Neon and the JSweet and Maven plugins.

**Comment by travelbasys** [comment]
Got it!
`
System.out.print
`
causes the above problem. But
`
System.out.println
`does not.
Whatever the reasons.

PS: Sorry if this is in the wrong forum: _jsweet_ might be the correct one.

**Comment by renaudpawlak** [comment]
Yes, that's indeed a JSweet issue :)
As you can see in the [default adapter](https://github.com/cincheo/jsweet/blob/522b0d8c410c1f83036851c8ee274ae3a6cf6044/transpiler/src/main/java/org/jsweet/transpiler/extension/Java2TypeScriptAdapter.java#L360), only ``println`` is supported.

This sort of partial support is kind of historic. In theory, all this should be done in the ``RemoveJavaDependenciesAdapter``. Also it is quite easy to develop your own adapter to support it and extend JSweet for your own needs.

To make it right, I think we should move the ``println`` support to ``RemoveJavaDependenciesAdapter`` and add the ``print`` support there... 

To avoid regressions, we can just add ``print`` support next to ``println`` support for now and move them in the next major release.

**Comment by renaudpawlak** [comment]
To be moved to JSweet.

**Comment by lgrignon** [comment]
Works on last JSweet Eclipse plugin version
