### ISSUE TITLE
Add to documentation that JDK is required

### ISSUE THREAD

**Issue by pascalheraud** [cincheo/jsweet-eclipse-plugin#21]
If I'm not wrong, Eclipse should be run with a JDK and not a JRE. It should be stated in documentation.

**Comment by lgrignon** [comment]
Even if I agree with this statement, I don't understand the link with JSweet? Could you enlighten me @pascalheraud please?

**Comment by pascalheraud** [comment]
Eclipse does not need to be run with a JDK, a simple JRE is enough.
If you run Eclipse with a JRE, Jsweet is not working, I think it needs the java compiler.

**Comment by lgrignon** [comment]
I see your point, but JSweet requires the JDK to work, because it depends on tools.jar AFAIR.

Let me rename your issue please.

I think we should have some kind of pretty warning but we will definitively not make JSweet work with a JRE.

**Comment by pascalheraud** [comment]
Yes a warning in installation instructions would be great :) I lost an hour looking for the reason it was not working.

**Comment by lgrignon** [comment]
Hehe, @renaudpawlak I was about to rename but I realize I don't have administration rights on this repo. Could you please grant me?
