### ISSUE TITLE
Please add the possiblity to set target version (e.g. es6) and module type (es2015)

### ISSUE THREAD

**Issue by orielmaute** [cincheo/jsweet-eclipse-plugin#23]
Currently the module type "es2015" cannot be selected. Please add it.
Also it would be great to set the javascript target version(es3, es5, es6).

**Comment by lgrignon** [comment]
Hello, this would be pretty easy but I won't have time. Do you want to PR?
We will take a look at your issues on the JSweet project
Thanks.

**Comment by lgrignon** [comment]
It should be good now, please see PR 
https://github.com/cincheo/jsweet-eclipse-plugin/pull/27

Eclipse update site has been redeployed
