### ISSUE TITLE
Cannot install plugin

### ISSUE THREAD

**Issue by JasonTheKitten** [cincheo/jsweet-eclipse-plugin#24]
Attempting to do so does not work. If you manually navigate to the URL in your browser, you get "Apache2 default page".

**Comment by zapappa** [comment]
Same problem - and if I manually navigate to "http://eclipse-update-site.jsweet.org" it goes to "www.jsweet.org/"

**Comment by JasonTheKitten** [comment]
Yea, it originally gave an apache error but now it just redirects you

**Comment by lgrignon** [comment]
Hello, I am trying to get it back right now :)

**Comment by lgrignon** [comment]
Thanks for reporting!

**Comment by lgrignon** [comment]
(That being said, I strongly recommend using Maven or Gradle plugin over Eclipse's plugin)

**Comment by lgrignon** [comment]
Hey guys, it should be ok now! @renaudpawlak only you can close this
