### ISSUE TITLE
Update JSweet Eclipse plugin to 2.2.0 and 2.3.0-SNAPSHOT

### ISSUE THREAD

**Issue by lgrignon** [cincheo/jsweet-eclipse-plugin#26]
Eclipse plugin is outdated. We need to update it to support last JSweet versions, and check that it works with last 2019 Eclipse versions.

This issue blocks a user here: https://github.com/cincheo/jsweet/issues/521

**Comment by lgrignon** [comment]
Other related issue: https://github.com/cincheo/jsweet/issues/522

**Comment by shamwoo** [comment]
how do I do that?

**Comment by lgrignon** [comment]
It should be good now, please see PR
https://github.com/cincheo/jsweet-eclipse-plugin/pull/27

Eclipse update site has been redeployed
