### ISSUE TITLE
Add a way to configure the JDK in the plugin

### ISSUE THREAD

**Issue by renaudpawlak** [cincheo/jsweet-eclipse-plugin#9]
At this point, JSweet necessarily uses the `JAVA_HOME` variable. We need a way to configure the JDK without having to change that variable (it is global and may conflict with other Java software).

My favorite method would be to simply get the path from the SDK used by the project, which would have to be a JDK >= 1.8.

As a fallback, we may have a configuration field to set the JDK path in the JSweet preferences.

**Comment by ivmarkov** [comment]
That would be my favorite as well. Have in mind that Eclipse does not need the JDK and can happily use a JRE as well (for obvious reasons). So perhaps the jsweet eclipse plugin should indicate to the user that the Java Runtime bound to the jsweet project is not really a JDK but a JRE.

**Comment by renaudpawlak** [comment]
The last commit should implement the "favorite" method. Probably need some feedback to see if it works for all cases.
